# Default server configuration.
host: 127.0.0.1
port: 3000
postgres:
  host: db
  port: 5432
  database_name: gesture_manager
  username: postgres
  password: gesture_manager_secret
  use_ssl: false
  time_zone: Asia/Shanghai

redis:
  host: kv
  port: 6379

jwt_secret: "OvA9SBLnncot8gFHvt8Gh1qkQ1ptGIQW"
password_salt: "Z5b84rrgsKmfNFNRExAC4BCJe5aZPdJq"