name: gsettings
version: 0.2.0

publish_to: none

description:
  GSettings client

homepage: https://github.com/canonical/gsettings.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dbus: ^0.6.0
  xdg_directories:
    path: ../xdg_directories

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.8
