version: "2.4"

services:
  kv:
    image: redis:alpine
    restart: always
    container_name: dgm_redis
    ports:
      - "6379:6379"
    networks:
      - dgm_api_default

  db:
    image: postgres:alpine
    restart: always
    container_name: dgm_postgres
    environment:
      POSTGRES_DB: gesture_manager
      POSTGRES_PASSWORD: gesture_manager_secret
    volumes:
      - ../db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dgm_api_default

  api:
    build: .
    image: dgm_api_image
    container_name: dgm_api
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - db
      - kv
    links:
      - db:db
      - kv:kv
    networks:
      - dgm_api_default

networks:
  dgm_api_default:
    name: dgm_api_default
